server:
    error:
      include-message: always
      include-binding-errors: always

spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/jollyday
      username: postgres
      password: licenta2024
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
      host: smtp.gmail.com
      port: 587
      username: bianca.a22f@gmail.com
      password: teouhdlcmpbgtplr
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      protocol: smtp
      test-connection: false